[package]
name = "dec13"
version = "0.1.0"
authors = ["Denys Vitali <denys@denv.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path="../../utils/" }
num = "0.3.1"
num-integer = "0.1.44"